try{
    hello()
} catch(error){
    console.log(error);
}

try{
    anotherFunction()
} catch{
    console.log("Este es un error");
}